#Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'VTO2Lib' do
    pod 'VTO2Lib'
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
